Repository Sadna-Market/Market, pull requests merged in 2022-05, with the labels that each got.

#132 fixed bug in AT
  Market/tests/Acceptance/Bridge/MarketBridge.java
  Market/tests/Acceptance/Bridge/ProxyMarket.java
  Market/tests/Acceptance/Bridge/RealMarket.java
  Market/tests/Acceptance/Tests/GuestBuyTests.java
  Market/tests/Acceptance/Tests/GuestGeneralTests.java
  Market/tests/Acceptance/Tests/MemberBuyTests.java
  Market/tests/Acceptance/Tests/PurchaseTest.java
  Market/tests/Acceptance/Tests/StoreManagerTests.java
  Market/tests/Acceptance/Tests/StoreOwnerTests.java
  Market/tests/Acceptance/Tests/SystemManagerTests.java
  Market/tests/Acceptance/Tests/SystemTests.java
Labels: bug

#133 Add files via upload libraries idea
  Market/.idea/libraries/javax_mail_1_6_2.xml
  Market/.idea/libraries/lib.xml
Labels: bug

#134 edit store and product type tests
  Files/version_1_files/~$rsion1.docx
  Market/src/main/System/Server/Domain/StoreModel/Store.java
  Market/tests/Integration/StoreAndProductType.java
Labels: documentation

#136 fix response code error
  Market/src/main/Service/Facade.java
Labels: bug

#147 Reject market version 1
  Files/version_1_files/white diagram.png
  Market/src/Stabs/UserManagerStab.java
  Market/src/log4j.properties
  Market/src/main/ErrorCode.java
  Market/src/main/ExternalService/SupplyService.java
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/src/main/System/Server/Domain/Market/Purchase.java
  Market/tests/main/System/Server/Domain/Market/MarketTest.java
  white diagram.drawio
Labels: bug, implementation, testing

#150 fix all Market rejects
  Market/src/Stabs/PurchaseStab.java
  Market/src/Stabs/UserManagerStab.java
  Market/src/main/ErrorCode.java
  Market/src/main/ExternalService/AbsExternalService.java
  Market/src/main/ExternalService/CreditCard.java
  Market/src/main/ExternalService/IExternalService.java
  Market/src/main/ExternalService/PaymentService.java
  Market/src/main/ExternalService/SupplyService.java
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/src/main/System/Server/Domain/Market/Purchase.java
  Market/src/main/System/Server/Domain/UserModel/Guest.java
  Market/src/main/System/Server/Domain/UserModel/User.java
  Market/src/main/System/Server/Domain/UserModel/UserManager.java
  Market/src/main/System/Server/Domain/UserModel/Validator.java
  Market/tests/main/System/Server/Domain/Market/MarketTest.java
Labels: bug, implementation, testing

#152 Update Purchase.java
  Market/src/main/System/Server/Domain/Market/Purchase.java
Labels: bug, implementation, testing

#153 add history in user
  Market/src/main/System/Server/Domain/UserModel/User.java
Labels: bug

#155 update architcture diagram and version1-fixed
  Files/version_1_files/Architcture Diagram.drawio
  Files/version_1_files/Version1-fixed.docx
  Files/version_1_files/architcure_diagram.jpg
Labels: documentation

#156 add SC
  Files/version_1_files/SC.drawio
  Files/version_1_files/SC.jpeg
  Files/version_1_files/SC.pdf
Labels: documentation

#157 Remove credit card class
  Market/src/Stabs/PurchaseStab.java
  Market/src/main/ExternalService/PaymentService.java
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/src/main/System/Server/Domain/Market/Purchase.java
  Market/tests/main/System/Server/Domain/ExternalServices/PurchaseUnitTest.java
  Market/tests/main/System/Server/Domain/Market/MarketTest.java
Labels: bug, implementation, testing

#158 integrationTest - Market
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/tests/Integration/StoreMarketTest.java
  Market/tests/Integration/UserMangerMarketTest.java
Labels: bug, testing

#159 fixed some bugs in tests
  Market/src/main/ExternalService/AbsExternalService.java
  Market/src/main/ExternalService/ExternalService.java
  Market/src/main/Service/Facade.java
  Market/src/main/Service/TestableFacade.java
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/src/main/System/Server/Domain/UserModel/UserManager.java
  Market/tests/Acceptance/Bridge/MarketBridge.java
  Market/tests/Acceptance/Bridge/ProxyMarket.java
  Market/tests/Acceptance/Bridge/RealMarket.java
  Market/tests/Acceptance/Obj/User.java
  Market/tests/Acceptance/Tests/GuestBuyTests.java
  Market/tests/Acceptance/Tests/MarketTests.java
  Market/tests/Acceptance/Tests/MemberBuyTests.java
  Market/tests/Acceptance/Tests/PurchaseTest.java
  Market/tests/Acceptance/Tests/StoreManagerTests.java
  Market/tests/Acceptance/Tests/StoreOwnerTests.java
  Market/tests/Acceptance/Tests/SystemManagerTests.java
  Market/tests/Acceptance/Tests/SystemTests.java
Labels: bug

#161 fixed some bugs in tests
  Market/src/main/ErrorCode.java
  Market/src/main/Service/Facade.java
  Market/src/main/Service/TestableFacade.java
  Market/src/main/System/Server/Domain/UserModel/UserManager.java
  Market/tests/Acceptance/Bridge/ProxyMarket.java
  Market/tests/Acceptance/Bridge/RealMarket.java
  Market/tests/Acceptance/Tests/GuestBuyTests.java
  Market/tests/Acceptance/Tests/GuestGeneralTests.java
  Market/tests/Acceptance/Tests/MarketTests.java
  Market/tests/Acceptance/Tests/MemberBuyTests.java
  Market/tests/Acceptance/Tests/PurchaseTest.java
  Market/tests/Acceptance/Tests/StoreManagerTests.java
  Market/tests/Acceptance/Tests/StoreOwnerTests.java
  Market/tests/Acceptance/Tests/SystemManagerTests.java
  Market/tests/Acceptance/Tests/SystemTests.java
Labels: bug, testing

#162 Change flag
  Market/src/Stabs/StoreStab.java
  Market/src/main/ErrorCode.java
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/tests/main/System/Server/Domain/Market/MarketTest.java
Labels: bug, testing

#163 fix get product signture
  Market/src/main/Service/Facade.java
  Market/src/main/Service/IMarket.java
  Market/src/main/Service/ServiceItem.java
  Market/src/main/System/Server/Domain/StoreModel/Inventory.java
  Market/src/main/System/Server/Domain/StoreModel/Store.java
Labels: bug

#164 Fix
  Market/src/main/Service/Facade.java
  Market/src/main/Service/IMarket.java
  Market/src/main/Service/ServiceItem.java
  Market/src/main/Service/ServiceShoppingCard.java
  Market/src/main/Service/TestableFacade.java
  Market/tests/Acceptance/Bridge/MarketBridge.java
  Market/tests/Acceptance/Bridge/ProxyMarket.java
  Market/tests/Acceptance/Bridge/RealMarket.java
  Market/tests/Acceptance/Tests/GuestBuyTests.java
  Market/tests/Acceptance/Tests/MemberBuyTests.java
  Market/tests/Acceptance/Tests/SystemTests.java
Labels: bug, testing

#165 #fronted-login and register page
  fronted/my-app/.gitignore
  fronted/my-app/.idea/.gitignore
  fronted/my-app/.idea/inspectionProfiles/Project_Default.xml
  fronted/my-app/.idea/misc.xml
  fronted/my-app/.idea/modules.xml
  fronted/my-app/.idea/my-app.iml
  fronted/my-app/.idea/vcs.xml
  fronted/my-app/README.md
  fronted/my-app/package-lock.json
  fronted/my-app/package.json
  fronted/my-app/public/favicon.ico
  fronted/my-app/public/index.html
  fronted/my-app/public/logo192.png
  fronted/my-app/public/logo512.png
  fronted/my-app/public/manifest.json
  fronted/my-app/public/robots.txt
  fronted/my-app/src/App.css
  fronted/my-app/src/App.js
  fronted/my-app/src/App.test.js
  fronted/my-app/src/components/initMarket.jsx
  fronted/my-app/src/components/login.jsx
  fronted/my-app/src/components/mainPage.jsx
  fronted/my-app/src/components/signUp.jsx
  fronted/my-app/src/index.css
  fronted/my-app/src/index.js
  fronted/my-app/src/logo.svg
  fronted/my-app/src/reportWebVitals.js
  fronted/my-app/src/setupTests.js
Labels: implementation

#168 fix AT
  Market/src/main/Service/Facade.java
  Market/tests/Acceptance/Bridge/RealMarket.java
  Market/tests/Acceptance/Tests/GuestBuyTests.java
  Market/tests/Acceptance/Tests/StoreOwnerTests.java
Labels: bug

#169 fix AT - open new store
  Market/tests/Acceptance/Bridge/RealMarket.java
Labels: bug

#171 fixed AT bugs
  Market/src/Stabs/StoreStab.java
  Market/src/main/ErrorCode.java
  Market/src/main/ExternalService/PaymentService.java
  Market/src/main/Service/Facade.java
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/src/main/System/Server/Domain/StoreModel/Inventory.java
  Market/src/main/System/Server/Domain/UserModel/ShoppingBag.java
  Market/src/main/System/Server/Domain/UserModel/ShoppingCart.java
  Market/tests/Acceptance/Bridge/ProxyMarket.java
  Market/tests/Acceptance/Bridge/RealMarket.java
  Market/tests/Acceptance/Tests/GuestBuyTests.java
  Market/tests/Acceptance/Tests/PurchaseTest.java
  Market/tests/Acceptance/Tests/StoreOwnerTests.java
Labels: bug, testing

#172 fixed AT bugs
  Market/src/main/ErrorCode.java
  Market/src/main/ExternalService/AbsExternalService.java
  Market/src/main/Service/Facade.java
  Market/src/main/Service/TestableFacade.java
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/src/main/System/Server/Domain/Market/PermissionManager.java
  Market/src/main/System/Server/Domain/Market/permissionType.java
  Market/src/main/System/Server/Domain/StoreModel/Inventory.java
  Market/src/main/System/Server/Domain/UserModel/ShoppingCart.java
  Market/src/main/System/Server/Domain/UserModel/UserManager.java
  Market/tests/Acceptance/Bridge/ProxyMarket.java
  Market/tests/Acceptance/Bridge/RealMarket.java
  Market/tests/Acceptance/Obj/Permission.java
  Market/tests/Acceptance/Tests/StoreManagerTests.java
  Market/tests/Acceptance/Tests/StoreOwnerTests.java
Labels: bug, testing

#173 added concurrent AT fixed #143
  Market/tests/Acceptance/Tests/ConcurrentAssignOwnerTest.java
  Market/tests/Acceptance/Tests/ConcurrentPurchaseTest.java
  Market/tests/Acceptance/Tests/ConcurrentRemoveProductAndPurchaseTest.java
Labels: testing

#174 Fix market search
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/src/main/System/Server/Domain/Market/Purchase.java
  Market/tests/main/System/Server/Domain/Market/MarketTest.java
Labels: bug, implementation, testing

#175 orgenize versions files
  Files/SC.jpg
  Files/version 0 - files/Architecture-componentD.pdf
  Files/version 0 - files/Glossary.docx
  Files/version 0 - files/UC-DANIEL.docx
  Files/version 0 - files/Usecase לדוגמא.docx
  Files/version 0 - files/Version0-fixed.docx
  Files/version 0 - files/Version0.docx
  Files/version 0 - files/Yaki USecases.docx
  Files/version 0 - files/classes textual information 2.iii.docx
  Files/version 0 - files/use case new daniel.docx
  Files/version 0 - files/use-cases-liel.docx
  Files/version 0 - files/usecases-Dor.docx
  Files/version 0 - files/~WRL2661.tmp
  Files/version 0 - files/אילוצים0.pdf
  Files/version 0 - files/חתימות על ההזת השעה.pdf
  Files/version 0 - files/מילון מונחים.docx
  Files/version 0 - files/תרחישי שימוש קנייה אורח מעודכן.docx
  Files/version 1 - files/Architcture Diagram.drawio
  Files/version 1 - files/DanielVersion1.docx
  Files/version 1 - files/SC.drawio
  Files/version 1 - files/SC.jpeg
  Files/version 1 - files/Version1-fixed.docx
  Files/version 1 - files/Version1.docx
  Files/version 1 - files/architcure_diagram.jpg
  Files/version 1 - files/white diagram.drawio
  Files/version 1 - files/white diagram.png
  Files/version 1 - files/דוח גרסה 1.docx
  Files/version 1 - files/מילון מונחים.docx
  Files/version 1 - files/סיכום מפגש - גרסה 1.pdf
  Files/version_1_files/SC.drawio
  Files/~$ki USecases.docx
  white diagram.drawio
  ~$rsion0.docx
Labels: documentation

#176 fix AT
  Market/src/main/Service/Facade.java
Labels: bug, testing

#177 fix AT and MarketStore tests and reset singletons
  Market/src/Stabs/UserManagerStab.java
  Market/src/main/ExternalService/AbsExternalService.java
  Market/src/main/ExternalService/ExternalService.java
  Market/src/main/ExternalService/PaymentService.java
  Market/src/main/ExternalService/SupplyService.java
  Market/src/main/Service/TestableFacade.java
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/src/main/System/Server/Domain/Market/PermissionManager.java
  Market/tests/Acceptance/Tests/ConcurrentAssignOwnerTest.java
  Market/tests/Acceptance/Tests/ConcurrentPurchaseTest.java
  Market/tests/Acceptance/Tests/ConcurrentRemoveProductAndPurchaseTest.java
  Market/tests/Acceptance/Tests/GuestBuyTests.java
  Market/tests/Acceptance/Tests/GuestGeneralTests.java
  Market/tests/Acceptance/Tests/MemberBuyTests.java
  Market/tests/Acceptance/Tests/PurchaseTest.java
  Market/tests/Acceptance/Tests/StoreManagerTests.java
  Market/tests/Acceptance/Tests/StoreOwnerTests.java
  Market/tests/Acceptance/Tests/SystemManagerTests.java
  Market/tests/Acceptance/Tests/SystemTests.java
  Market/tests/Integration/StoreMarketTest.java
Labels: bug, testing

#179 Fix
  Market/src/main/Service/Facade.java
  Market/src/main/Service/IMarket.java
  Market/tests/Acceptance/Bridge/RealMarket.java
  Market/tests/Acceptance/Tests/GuestBuyTests.java
  Market/tests/Integration/StoreMarketTest.java
  Market/tests/Integration/UserMangerMarketTest.java
  Market/tests/main/System/Server/Domain/Market/MarketTest.java
  Market/tests/main/System/Server/Domain/Market/ProductTypeTest.java
Labels: bug, testing

#180 delete order test - integration
  Market/tests/Integration/StoreMarketTest.java
Labels: testing

#182 main page
  fronted/my-app/src/App.js
  fronted/my-app/src/components/login.jsx
  fronted/my-app/src/components/mainPage.jsx
Labels: implementation

#184 fixed arichture diagram
  Files/version 0 - files/Architcture Diagram.drawio
  Files/version 0 - files/Architecture-componentD.pdf
  Files/version 0 - files/Version0-fixed.docx
  Files/version 0 - files/Version0.docx
  Files/version 1 - files/Architcture Diagram.drawio
  Files/version 1 - files/Version1-fixed.docx
  Files/version 1 - files/Version1.docx
Labels: documentation

#190 fixed market tests
  Market/tests/main/System/Server/Domain/Market/MarketTest.java
Labels: bug, testing

#192 fixed market tests
  Market/tests/main/System/Server/Domain/Market/MarketTest.java
Labels: bug, testing

#198 add http request
  market-spring-boot/src/main/frontend/clientHttp.js
  market-spring-boot/src/main/frontend/package.json
  market-spring-boot/src/main/java/com/example/demo/api/Iapi.java
  market-spring-boot/src/main/java/com/example/demo/api/api.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/apiUser.java
Labels: implementation

#199 brige fix
  market-spring-boot/src/main/frontend/clientHttp.js
  market-spring-boot/src/main/java/com/example/demo/api/api.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
Labels: bug

#203 fix http
  market-spring-boot/src/main/frontend/clientHttp.js
  market-spring-boot/src/main/java/com/example/demo/DemoApplication.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/api/Iapi.java
  market-spring-boot/src/main/java/com/example/demo/api/api.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/apiShoppingBag.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/apiUser.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
Labels: bug

#204 #166
  Front End/my-app/.idea/.gitignore
  Front End/my-app/package-lock.json
  Front End/my-app/package.json
  Front End/my-app/src/App.js
  Front End/my-app/src/client/clientHttp.js
  Front End/my-app/src/components/Bar/Bar.js
  Front End/my-app/src/components/Manager/SignUpManager.js
  Front End/my-app/src/components/Manager/test.js
  Front End/my-app/src/components/Market/Market.js
  Front End/my-app/src/components/Store/StoreList.js
  Front End/my-app/src/index.js
Labels: UI

#205 #166 add http connection
  Front End/my-app/src/App.js
  Front End/my-app/src/client/clientHttp.js
  Front End/my-app/src/components/Bar/Bar.js
  Front End/my-app/src/components/Bar/SignUp.js
  Front End/my-app/src/components/Manager/SignUpManager.js
  market-spring-boot/src/main/java/com/example/demo/api/api.java
Labels: UI

#211 Alert service
  Files/version 2 - files/Architcture Diagram.drawio
  Files/version 2 - files/Version2.docx
  Files/version 2 - files/white diagram.drawio
  market-spring-boot/pom.xml
  market-spring-boot/src/main/Alerts/.gitignore
  market-spring-boot/src/main/java/Stabs/UserManagerStab.java
  market-spring-boot/src/main/java/com/example/demo/DemoApplication.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/AlertService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/Notification.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/NotificationController.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/NotificationDispatcher.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/WebSocketConfig.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/PermissionManager.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/permissionType.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Inventory.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/User.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/UserManager.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/Validator.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/IMarket.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/ServiceProductStore.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/ServiceProductType.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/ServiceUser.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/MarketBridge.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/ProxyMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/RealMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Obj/User.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/SystemManagerTests.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/SystemTests.java
  market-spring-boot/src/test/java/com/example/Integration/UserMangerMarketTest.java
  market-spring-boot/src/test/java/com/example/Unit/UserModel/UserTest.java
  market-spring-boot/src/test/java/com/example/demo/DemoApplicationTests.java
Labels: implementation

#212 Http connection to fronend
  Front End/my-app/src/App.js
  Front End/my-app/src/client/clientHttp.js
  Front End/my-app/src/components/Bar/Bar.js
  Front End/my-app/src/components/Bar/SignUp.js
  Front End/my-app/src/components/Manager/SignUpManager.js
  Front End/my-app/src/components/Market/Market.js
Labels: UI

#213 https client add functions
  market-spring-boot/src/main/java/com/example/demo/api/Iapi.java
  market-spring-boot/src/main/java/com/example/demo/api/api.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/apiUser.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
Labels: implementation

#214 Cancel mem
  Files/version 2 - files/Version2.docx
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/AlertService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/ErrorCode.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Permission.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/PermissionManager.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/permissionType.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/UserManager.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/IMarket.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/MarketBridge.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/ProxyMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/RealMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/SystemManagerTests.java
  market-spring-boot/src/test/java/com/example/Unit/UserModel/UserManagerTest.java
Labels: implementation, testing

#215 Http connection to fronend
  Front End/my-app/src/App.js
  Front End/my-app/src/client/clientHttp.js
  Front End/my-app/src/components/Bar/Bar.js
  Front End/my-app/src/components/Bar/SignUp.js
  Front End/my-app/src/components/Manager/SignUpManager.js
  Front End/my-app/src/components/Market/Market.js
  Front End/my-app/src/components/Store/StoreList.js
  Front End/my-app/src/components/Store/newStore.js
  market-spring-boot/src/main/java/com/example/demo/api/api.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
Labels: UI

#217 #186 Remove owner permission
  Files/version 2 - files/Architcture Diagram.drawio
  Files/version 2 - files/Version2.docx
  Files/version 2 - files/white diagram.drawio
  market-spring-boot/src/main/java/com/example/demo/Domain/ErrorCode.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/PermissionManager.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/permissionType.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/UserManager.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/IMarket.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/MarketBridge.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/ProxyMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/RealMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/PurchaseTest.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/StoreOwnerTests.java
  market-spring-boot/src/test/java/com/example/Unit/Market/PermissionManagerTest.java
Labels: documentation, implementation

#225 #166 connect almost all http connection
  Front End/my-app/src/App.js
  Front End/my-app/src/ErrorCodeGui.js
  Front End/my-app/src/client/clientHttp.js
  Front End/my-app/src/components/Bar/Bar.js
  Front End/my-app/src/components/Bar/SignUp.js
  Front End/my-app/src/components/Cart/BuyCart.js
  Front End/my-app/src/components/Cart/MyCart.js
  Front End/my-app/src/components/Manager/SignUpManager.js
  Front End/my-app/src/components/Market/Market.js
  Front End/my-app/src/components/Market/MarketButton.js
  Front End/my-app/src/components/Market/Password.js
  Front End/my-app/src/components/Market/Profile.js
  Front End/my-app/src/components/Product/ProductInStore.js
  Front End/my-app/src/components/Product/ProductInStoreList.js
  Front End/my-app/src/components/Product/ProductList.js
  Front End/my-app/src/components/Store/AddManager.js
  Front End/my-app/src/components/Store/EditPermission.js
  Front End/my-app/src/components/Store/EditProduct.js
  Front End/my-app/src/components/Store/HistoryInStore.js
  Front End/my-app/src/components/Store/NewProductInStore.js
  Front End/my-app/src/components/Store/RemoveProduct.js
  Front End/my-app/src/components/Store/Store.js
  Front End/my-app/src/components/Store/StoreList.js
  Front End/my-app/src/components/Store/closeStore.js
  Front End/my-app/src/components/Store/newStore.js
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/ServiceStore.java
Labels: UI

#228 fixed bug in create store
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/RealMarket.java
Labels: bug

#227 Httm discout bypolicy
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/ServiceHistory.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/ServiceShoppingBag.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/ServiceShoppingCart.java
  market-spring-boot/src/main/java/com/example/demo/api/Iapi.java
  market-spring-boot/src/main/java/com/example/demo/api/api.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
Labels: implementation
