Repository Sadna-Market/Market, pull requests merged in 2022-04, with the labels that each got.

#15 #2 Edited component diagram
  Architecture-componentD.pdf
  white diagram.drawio
Labels: documentation

#17 fixed #16 testing issue
  README.md
Labels: documentation

#21 fix White diagram fixed #1
  white diagram.drawio
Labels: documentation

#24 whiteDiagram Fix Reject
  white diagram.drawio
Labels: implementation

#22 Service level requests fixed #12
  Files/Yaki USecases.docx
  Files/~$ki USecases.docx
  Files/~WRL2661.tmp
Labels: documentation

#27 fixed #5 edited use cases like example
  Files/תרחישי שימוש קנייה אורח מעודכן.docx
  Files/תרחישי שימוש קנייה אורח.docx
Labels: documentation

#31 Use case repair
  Files/SC.drawio
  Files/SC.jpg
  Files/use-cases-liel.docx
  Files/מילון מונחים.docx
Labels: documentation

#67 fixed #66 installed junit5 + mockito.
  Market/.idea/libraries/junit_jupiter.xml
  Market/.idea/libraries/mockito_all.xml
  Market/.idea/runConfigurations.xml
  Market/.idea/workspace.xml
  Market/Market.iml
  Market/lib/apiguardian-api-1.0.0.jar
  Market/lib/junit-jupiter-5.4.2.jar
  Market/lib/junit-jupiter-api-5.4.2.jar
  Market/lib/junit-jupiter-engine-5.4.2.jar
  Market/lib/junit-jupiter-params-5.4.2.jar
  Market/lib/junit-platform-commons-1.4.2.jar
  Market/lib/junit-platform-engine-1.4.2.jar
  Market/lib/mockito-all-1.9.0.jar
  Market/lib/opentest4j-1.1.1.jar
Labels: testing

#93 fix erro user moudule
  Market/.idea/workspace.xml
  Market/out/production/Market/main/ErrorCode.class
  Market/out/production/Market/main/System/Server/Domain/Facade.class
  Market/out/production/Market/main/System/Server/Domain/Market/ErrorCode.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/UserManager.class
  Market/out/test/Market/main/System/Server/Domain/UserModel/UserManagerTest.class
  Market/src/main/ErrorCode.java
  Market/src/main/System/Server/Domain/Facade.java
  Market/src/main/System/Server/Domain/Market/ErrorCode.java
  Market/src/main/System/Server/Domain/UserModel/UserManager.java
  Market/tests/main/System/Server/Domain/UserModel/UserManagerTest.java
Labels: bug, implementation, testing

#95 Market change to response #36
  Market/.idea/workspace.xml
  Market/out/production/Market/Stabs/StoreStab.class
  Market/out/production/Market/Stabs/UserManagerStab.class
  Market/out/production/Market/main/Service/IMarket.class
  Market/out/production/Market/main/System/Server/Domain/Facade.class
  Market/out/production/Market/main/System/Server/Domain/Market/Market.class
  Market/out/production/Market/main/System/Server/Domain/Market/Purchase.class
  Market/out/production/Market/main/System/Server/Domain/Market/SaleObj.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/Response/ATResponse.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/Response/ATResponseObj.class
  Market/out/test/Market/main/System/Server/Domain/Market/MarketTest.class
  Market/src/Stabs/StoreStab.java
  Market/src/Stabs/UserManagerStab.java
  Market/src/main/System/Server/Domain/Facade.java
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/src/main/System/Server/Domain/Market/Purchase.java
  Market/src/main/System/Server/Domain/Market/SaleObj.java
  Market/src/main/System/Server/Domain/UserModel/Response/ATResponse.java
  Market/src/main/System/Server/Domain/UserModel/Response/ATResponseObj.java
  Market/src/main/System/Server/Domain/UserModel/ShoppingBag.java
  Market/tests/main/System/Server/Domain/Market/MarketTest.java
Labels: bug, implementation, testing

#96 add sync in store and inventory + response
  Market/.idea/workspace.xml
  Market/out/production/Market/main/System/Server/Domain/Facade.class
  Market/out/production/Market/main/System/Server/Domain/Market/DataResponse.class
  Market/out/production/Market/main/System/Server/Domain/Market/Market.class
  Market/out/production/Market/main/System/Server/Domain/Market/PermissionManager$PermissionManagerWrapper.class
  Market/out/production/Market/main/System/Server/Domain/Market/PermissionManager.class
  Market/out/production/Market/main/System/Server/Domain/Market/Purchase.class
  Market/out/production/Market/main/System/Server/Domain/Market/Response.class
  Market/out/production/Market/main/System/Server/Domain/Market/userTypes.class
  Market/out/production/Market/main/System/Server/Domain/StoreModel/Discount.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/Guest.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/Response/ATResponse.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/Response/ATResponseObj.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/Response/ProductResponse.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/Response/StoreResponse.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/ShoppingBag.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/ShoppingCart.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/User.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/UserManager.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/Validator.class
  Market/out/production/Market/main/System/Server/Domain/UserModel/userTypes.class
  Market/src/main/System/Server/Domain/StoreModel/Inventory.java
  Market/src/main/System/Server/Domain/StoreModel/Store.java
  Market/tests/main/System/Server/Domain/StoreModel/InventoryTest.java
  Market/tests/main/System/Server/Domain/StoreModel/StoreTest.java
Labels: implementation

#99 #38 add error code
  Market/.idea/workspace.xml
  Market/src/main/ErrorCode.java
  Market/src/main/System/Server/Domain/StoreModel/Inventory.java
  Market/src/main/System/Server/Domain/StoreModel/Store.java
Labels: implementation

#100 #53 add fun that set the quantity in inverntory
  Market/.idea/workspace.xml
  Market/src/main/System/Server/Domain/StoreModel/Inventory.java
  Market/src/main/System/Server/Domain/StoreModel/Store.java
Labels: implementation

#101 Acceptance Tests #10
  .idea/Market.iml
  Market/.idea/runConfigurations.xml
  Market/.idea/workspace.xml
  Market/tests/Acceptance/Bridge/MarketBridge.java
  Market/tests/Acceptance/Bridge/ProxyMarket.java
  Market/tests/Acceptance/Bridge/RealMarket.java
  Market/tests/Acceptance/Obj/ATResponse.java
  Market/tests/Acceptance/Obj/ATResponseObj.java
  Market/tests/Acceptance/Obj/Address.java
  Market/tests/Acceptance/Obj/CreditCard.java
  Market/tests/Acceptance/Obj/ItemDetail.java
  Market/tests/Acceptance/Obj/PasswordGenerator.java
  Market/tests/Acceptance/Obj/Permission.java
  Market/tests/Acceptance/Obj/User.java
  Market/tests/Acceptance/Tests/GuestBuyTests.java
  Market/tests/Acceptance/Tests/GuestGeneralTests.java
  Market/tests/Acceptance/Tests/MarketTests.java
  Market/tests/Acceptance/Tests/MemberBuyTests.java
  Market/tests/Acceptance/Tests/PurchaseTest.java
  Market/tests/Acceptance/Tests/StoreManagerTests.java
  Market/tests/Acceptance/Tests/StoreOwnerTests.java
  Market/tests/Acceptance/Tests/SystemManagerTests.java
  Market/tests/Acceptance/Tests/SystemTests.java
Labels: testing

#104 package refactoring + minor changes
  Market/.idea/workspace.xml
  Market/src/Stabs/StoreStab.java
  Market/src/Stabs/UserManagerStab.java
  Market/src/main/Service/Facade.java
  Market/src/main/Service/IMarket.java
  Market/src/main/Service/ServiceHistory.java
  Market/src/main/Service/ServiceShoppingCard.java
  Market/src/main/Service/ServiceStore.java
  Market/src/main/System/Server/Domain/Market/DataResponse.java
  Market/src/main/System/Server/Domain/Market/PermissionManager.java
  Market/src/main/System/Server/Domain/Market/Purchase.java
  Market/src/main/System/Server/Domain/Market/Response.java
  Market/src/main/System/Server/Domain/Response/DResponse.java
  Market/src/main/System/Server/Domain/Response/DResponseObj.java
  Market/src/main/System/Server/Domain/Response/ProductResponse.java
  Market/src/main/System/Server/Domain/Response/ShoppingCartResponse.java
  Market/src/main/System/Server/Domain/Response/StoreResponse.java
  Market/src/main/System/Server/Domain/StoreModel/Inventory.java
  Market/src/main/System/Server/Domain/StoreModel/ProductStore.java
  Market/src/main/System/Server/Domain/StoreModel/Store.java
  Market/src/main/System/Server/Domain/UserModel/Response/ATResponseObj.java
  Market/src/main/System/Server/Domain/UserModel/Response/ProductResponse.java
  Market/src/main/System/Server/Domain/UserModel/Response/ShoppingCartResponse.java
  Market/src/main/System/Server/Domain/UserModel/Response/StoreResponse.java
  Market/src/main/System/Server/Domain/UserModel/User.java
  Market/src/main/System/Server/Domain/UserModel/UserManager.java
Labels: bug

#105 #35 NewResponse
  Market/src/main/Service/Facade.java
  Market/src/main/Service/SLRespons.java
  Market/src/main/Service/SLResponsOBJ.java
  Market/src/main/System/Server/Domain/Market/PermissionManager.java
  Market/src/main/System/Server/Domain/Response/DResponse.java
  Market/src/main/System/Server/Domain/Response/DResponseObj.java
Labels: implementation

#107 Market reject #36
  Market/.idea/runConfigurations.xml
  Market/.idea/workspace.xml
  Market/out/production/Market/META-INF/Market.kotlin_module
  Market/out/production/Market/Stabs/StoreStab.class
  Market/out/production/Market/Stabs/UserManagerStab.class
  Market/out/production/Market/main/Service/IMarket.class
  Market/out/production/Market/main/System/Server/Domain/Market/ProductType.class
  Market/out/test/Market/main/System/Server/Domain/Market/MarketTest.class
  Market/out/test/Market/main/System/Server/Domain/Market/ProductTypeTest.class
  Market/src/Stabs/StoreStab.java
  Market/src/main/Service/Facade.java
  Market/src/main/Service/IMarket.java
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/src/main/System/Server/Domain/Market/ProductType.java
  Market/src/main/System/Server/Domain/Market/permissionType.java
  Market/tests/main/System/Server/Domain/Market/MarketTest.java
  Market/tests/main/System/Server/Domain/Market/ProductTypeTest.java
Labels: bug, implementation, testing

#111 fix bug in inventory
  Market/.idea/workspace.xml
  Market/src/Stabs/ProductTypeStab.java
  Market/src/main/System/Server/Domain/StoreModel/Inventory.java
  Market/tests/Integration/InventoryAndProductType.java
  Market/tests/Integration/StoreAndProductType.java
  Market/tests/main/System/Server/Domain/StoreModel/InventoryTest.java
  Market/tests/main/System/Server/Domain/StoreModel/StoreTest.java
Labels: bug, implementation

#115 Test
  Market/.idea/runConfigurations.xml
  Market/src/Stabs/ProductTypeStab.java
  Market/src/main/System/Server/Domain/StoreModel/Inventory.java
  Market/src/main/System/Server/Domain/StoreModel/ProductStore.java
  Market/src/main/System/Server/Domain/StoreModel/Store.java
  Market/tests/Integration/StoreAndProductType.java
  Market/tests/main/System/Server/Domain/StoreModel/StoreTest.java
Labels: bug, implementation

#116 update diagram
  white diagram.drawio
  ~$rsion0-fixed.docx
Labels: documentation

#117 update diagram
  Files/version_1_files/architcure_diagram.jpg
Labels: documentation

#118 Market reject #36 #41 #42 connect ExternalServices
  Market/src/Stabs/StoreStab.java
  Market/src/Stabs/UserManagerStab.java
  Market/src/main/ErrorCode.java
  Market/src/main/ExternalService/AbsExternalService.java
  Market/src/main/ExternalService/CreditCard.java
  Market/src/main/ExternalService/ExternalService.java
  Market/src/main/ExternalService/IExternalService.java
  Market/src/main/ExternalService/PaymentService.java
  Market/src/main/ExternalService/SupplyService.java
  Market/src/main/Service/ServiceStore.java
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/src/main/System/Server/Domain/Market/PermissionManager.java
  Market/src/main/System/Server/Domain/Market/ProductType.java
  Market/src/main/System/Server/Domain/Market/Purchase.java
  Market/src/main/System/Server/Domain/StoreModel/Store.java
  Market/tests/Integration/StoreAndProductType.java
Labels: bug, implementation, testing

#119 Market reject #36 #41
  Market/src/main/ErrorCode.java
  Market/src/main/ExternalService/CreditCard.java
  Market/src/main/ExternalService/ExternalService.java
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/src/main/System/Server/Domain/Market/Purchase.java
  Market/tests/main/System/Server/Domain/ExternalServices/PurchaseUnitTest.java
Labels: bug, implementation, testing

#121 compiled success
  Market/src/main/ErrorCode.java
  Market/src/main/Service/Facade.java
  Market/src/main/Service/IMarket.java
  Market/src/main/Service/ServiceHistory.java
  Market/src/main/Service/ServiceItem.java
  Market/src/main/Service/ServiceShoppingCard.java
  Market/src/main/Service/ServiceUser.java
  Market/src/main/Service/ServiseItem.java
  Market/src/main/Service/TestableFacade.java
  Market/src/main/System/Server/Domain/UserModel/UserManager.java
  Market/tests/Acceptance/Bridge/MarketBridge.java
  Market/tests/Acceptance/Bridge/ProxyMarket.java
  Market/tests/Acceptance/Bridge/RealMarket.java
  Market/tests/Acceptance/Obj/ATResponseObj.java
  Market/tests/Acceptance/Obj/ItemDetail.java
  Market/tests/Acceptance/Tests/GuestBuyTests.java
  Market/tests/Acceptance/Tests/GuestGeneralTests.java
  Market/tests/Acceptance/Tests/MarketTests.java
  Market/tests/Acceptance/Tests/MemberBuyTests.java
  Market/tests/Acceptance/Tests/PurchaseTest.java
  Market/tests/Acceptance/Tests/StoreManagerTests.java
  Market/tests/Acceptance/Tests/StoreOwnerTests.java
  Market/tests/Acceptance/Tests/SystemManagerTests.java
  Market/tests/Acceptance/Tests/SystemTests.java
Labels: bug

#123 fixed#88 update dictionary
  Files/version_1_files/מילון מונחים.docx
Labels: documentation

#124 Reject white diagram fixed #84
  Files/version_1_files/white diagram.png
  Market/src/main/System/Server/Domain/Market/Market.java
  white diagram.drawio
Labels: bug, documentation

#126 #85 fixed update Architecture Diagram
  Files/version_1_files/Architcture Diagram.drawio
  white diagram.drawio
  ~$rsion0-fixed.docx
Labels: documentation

#127 fixed #78 - added version1 doc
  Files/version_1_files/Version1.docx
Labels: documentation

#128 fixed response bug
  Market/src/main/Service/Facade.java
  Market/src/main/Service/SLResponsOBJ.java
  Market/src/main/System/Server/Domain/Market/Market.java
  Market/tests/Acceptance/Bridge/ProxyMarket.java
  Market/tests/Acceptance/Bridge/RealMarket.java
  Market/tests/Acceptance/Tests/MarketTests.java
Labels: bug

#129 fixed #83, fixed #36, fixed #41 ,fixed #42 , fixed #37 , fixed #40
  Market/src/main/System/Server/Domain/Market/Market.java
Labels: bug, implementation, testing

#130 added SC
  Files/version_1_files/SC.pdf
Labels: documentation

#131 fixed #90 version report
  Files/version_1_files/check.txt
  Files/version_1_files/~$rsion1.docx
  Files/version_1_files/דוח גרסה 1.docx
Labels: documentation
