Repository Sadna-Market/Market, pull requests merged in 2022-06, with the labels that each got.

#230 get policies rules and bugs
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyPolicy.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/AndBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/BuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/CategoryBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/CompositionBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/ConditioningBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/LeafBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/OrBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/ProductBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/ShoppingBagBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/UserBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountPolicy.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/AddDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/AndDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/CompositionDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/ConditionCategoryDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/ConditionProductDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/ConditionStoreDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/DiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/LeafDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/OrDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/SimpleCategoryDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/SimpleProductDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/SimpleStoreDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/XorDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Predicate/CategoryPred.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Predicate/Predicate.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Predicate/ProductPred.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Predicate/ShoppingBagPred.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Predicate/UserPred.java
  market-spring-boot/src/test/java/com/example/Unit/StoreModel/DiscountPoilicyTest.java
Labels: bug, implementation

#231 #186 fixed remove owner permission
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/UserManager.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/PurchaseTest.java
  market-spring-boot/src/test/java/com/example/Unit/Market/PermissionManagerTest.java
Labels: implementation

#232 React
  Front End/my-app/src/components/BuyingPolicy/AddSimpleRule.js
  Front End/my-app/src/components/BuyingPolicy/ComposeRules/AddComposeRule.js
  Front End/my-app/src/components/BuyingPolicy/ComposeRules/AddRule.js
  Front End/my-app/src/components/BuyingPolicy/ComposeRules/ComposeRuleID.css
  Front End/my-app/src/components/BuyingPolicy/ComposeRules/ComposeRuleID.js
  Front End/my-app/src/components/BuyingPolicy/ComposeRules/ComposeRuleList.js
  Front End/my-app/src/components/BuyingPolicy/ComposeRules/ConditionRule.css
  Front End/my-app/src/components/BuyingPolicy/ComposeRules/ConditionRule.js
  Front End/my-app/src/components/BuyingPolicy/ComposeRules/OrRule.js
  Front End/my-app/src/components/BuyingPolicy/RuleID.js
  Front End/my-app/src/components/BuyingPolicy/RuleInfo.css
  Front End/my-app/src/components/BuyingPolicy/RuleInfo.js
  Front End/my-app/src/components/BuyingPolicy/RuleList.js
  Front End/my-app/src/components/BuyingPolicy/SimpleCompose/AddRule.js
  Front End/my-app/src/components/BuyingPolicy/SimpleCompose/AddSimpleCompose.js
  Front End/my-app/src/components/BuyingPolicy/SimpleCompose/ConditionRule.js
  Front End/my-app/src/components/BuyingPolicy/SimpleCompose/MoreRule.css
  Front End/my-app/src/components/BuyingPolicy/SimpleCompose/MoreRule.js
  Front End/my-app/src/components/BuyingPolicy/SimpleCompose/OrRule.js
  Front End/my-app/src/components/BuyingPolicy/buyingPolicy.js
  Front End/my-app/src/components/BuyingPolicy/simpleBuyingRules/CategoryRule.js
  Front End/my-app/src/components/BuyingPolicy/simpleBuyingRules/ProductRule.js
  Front End/my-app/src/components/BuyingPolicy/simpleBuyingRules/ShoppingBagRules.js
  Front End/my-app/src/components/BuyingPolicy/simpleBuyingRules/UserRule.js
  Front End/my-app/src/components/DiscountPolicy/AllRules.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/AddCombineRule.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/AddRule.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/AndRule.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/CombineRuleID.css
  Front End/my-app/src/components/DiscountPolicy/CombineRules/CombineRuleID.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/CombineRuleList.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/OrRule.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/XorRule.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/AddComposeDiscount.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/AddRule.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/AndRule.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/MoreRule.css
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/MoreRule.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/OrRule.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/XorRule.js
  Front End/my-app/src/components/DiscountPolicy/RuleID.js
  Front End/my-app/src/components/DiscountPolicy/RuleInfo.css
  Front End/my-app/src/components/DiscountPolicy/RuleInfo.js
  Front End/my-app/src/components/DiscountPolicy/RuleList.js
  Front End/my-app/src/components/DiscountPolicy/SimpleRules/AddSimpleRule.js
  Front End/my-app/src/components/DiscountPolicy/SimpleRules/CategoryDiscountRule.js
  Front End/my-app/src/components/DiscountPolicy/SimpleRules/ConditionCategoryDiscountRule.js
  Front End/my-app/src/components/DiscountPolicy/SimpleRules/ConditionProductDiscountRule.js
  Front End/my-app/src/components/DiscountPolicy/SimpleRules/ConditionStoreDiscountRule.js
  Front End/my-app/src/components/DiscountPolicy/SimpleRules/ProductDiscountRule.js
  Front End/my-app/src/components/DiscountPolicy/SimpleRules/SimpleDisountRule.js
  Front End/my-app/src/components/Manager/ManagerButton.js
  Front End/my-app/src/components/Market/Market.css
  Front End/my-app/src/components/Store/BuyingPolicy.js
  Front End/my-app/src/components/Store/DiscountPolicy.js
  Front End/my-app/src/components/Store/Store.css
  Front End/my-app/src/components/Store/Store.js
Labels: UI

#233 #166
  Front End/my-app/src/client/clientHttp.js
  Front End/my-app/src/components/Cart/BuyCart.js
  Front End/my-app/src/components/Manager/ManagerButton.js
  Front End/my-app/src/components/Manager/NewProductType.js
  Front End/my-app/src/components/Manager/UserID.js
  Front End/my-app/src/components/Market/Market.js
  Front End/my-app/src/components/Market/Password.js
  Front End/my-app/src/components/Market/Profile.js
  Front End/my-app/src/components/Product/ProductList.js
Labels: UI

#235 Da - #234
  Files/version 2 - files/UI specifications.docx
  Files/version 2 - files/UI specifications.pdf
  Files/version 2 - files/white diagram.drawio
  market-spring-boot/pom.xml
  market-spring-boot/src/main/java/com/example/demo/DataAccess/CompositeKeys/PermissionId.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/CompositeKeys/ShoppingBagId.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataBuyPolicy.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataDiscountPolicy.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataHistory.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataInventory.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataPermission.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataProductStore.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataProductType.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataShoppingBag.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataShoppingCart.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataStore.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataUser.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Enums/PermissionType.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Enums/UserType.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/BuyPolicyRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/DiscountPolicyRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/HistoryRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/InventoryRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/PermissionRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/ProductStoreRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/ProductTypeRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/ShoppingBagRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/ShoppingCartRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/StoreRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/UserRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/UserService.java
  market-spring-boot/src/main/java/com/example/demo/DemoApplication.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/AlertService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/AlertServiceDemo.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/IAlertService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/NotificationController.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/NotificationDispatcher.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/History.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/UserManager.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/ServiceHistory.java
  market-spring-boot/src/main/java/com/example/demo/api/api.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
  market-spring-boot/src/main/resources/application.properties
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/MarketTests.java
Labels: bug, implementation

#236 Notification #219
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/UserService.java
  market-spring-boot/src/main/java/com/example/demo/DemoApplication.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/AlertService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/NotificationDispatcher.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/WebSocketConfig.java
Labels: bug

#242 #185 AT of policies
  market-spring-boot/src/main/java/com/example/demo/Domain/ErrorCode.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountPolicy.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/AndDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/CompositionDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/ConditionProductDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/DiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/LeafDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/OrDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/XorDiscountRule.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/MarketBridge.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/ProxyMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/RealMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Obj/History.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/PurchaseTest.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/StoreManagerTests.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/StoreOwnerTests.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/SystemManagerTests.java
  market-spring-boot/src/test/java/com/example/Unit/StoreModel/DiscountPoilicyTest.java
Labels: bug, implementation

#243 Http connection to fronend
  Front End/my-app/package-lock.json
  Front End/my-app/package.json
  Front End/my-app/src/App.css
  Front End/my-app/src/App.js
  Front End/my-app/src/client/clientHttp.js
  Front End/my-app/src/components/Bar/Bar.js
  Front End/my-app/src/components/Market/Market.js
  Front End/my-app/src/components/Market/Profile.js
  Front End/my-app/src/components/Product/FilterProductList.js
  Front End/my-app/src/components/Product/ProductList.js
  Front End/my-app/src/components/Store/EditProduct.js
  Front End/my-app/src/components/Store/RemoveManager.js
  Front End/my-app/src/index.js
Labels: implementation

#246 Http connection to fronend
  Files/version 3 -files/Load and stress system test.pptx
  Front End/my-app/src/App.js
  Front End/my-app/src/client/clientHttp.js
  Front End/my-app/src/components/Bar/Bar.js
  Front End/my-app/src/components/Bar/SignUp.js
  Front End/my-app/src/components/Manager/UserID.js
  Front End/my-app/src/components/Market/Market.js
  Front End/my-app/src/components/Market/Profile.js
  Front End/my-app/src/components/Product/FilterProductList.js
  Front End/my-app/src/components/Product/ProductInStore.js
  Front End/my-app/src/components/Product/ProductInStoreList.js
  Front End/my-app/src/components/Store/AddManager.js
  Front End/my-app/src/components/Store/HistoryInStore.js
  Front End/my-app/src/components/Store/NewProductInStore.js
  Front End/my-app/src/components/Store/RemoveManager.js
  Front End/my-app/src/components/Store/Rules.js
  Front End/my-app/src/components/Store/Store.js
  Front End/my-app/src/components/Store/StoreID.js
Labels: UI

#245 #241 Submission of a purchase offer
  Files/version 3 - files/Version3.docx
  Files/version 3 - files/white diagram.drawio
  market-spring-boot/src/main/java/com/example/demo/Domain/ErrorCode.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Purchase.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/permissionType.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BID.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountPolicy.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Store.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/IMarket.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
  market-spring-boot/src/test/java/com/example/Integration/StoreAndPolicies.java
  market-spring-boot/src/test/java/com/example/Unit/StoreModel/DiscountPoilicyTest.java
Labels: implementation

#249 Supply pay api
  market-spring-boot/src/main/java/com/example/demo/Domain/ErrorCode.java
  market-spring-boot/src/main/java/com/example/demo/ExternalService/AbsExternalService.java
  market-spring-boot/src/main/java/com/example/demo/ExternalService/PaymentService.java
  market-spring-boot/src/main/java/com/example/demo/ExternalService/SupplyService.java
  market-spring-boot/src/test/java/com/example/Unit/ExternalServices/AbsExternalServiceTest.java
  market-spring-boot/src/test/java/com/example/Unit/ExternalServices/PaymentServiceTest.java
  market-spring-boot/src/test/java/com/example/Unit/ExternalServices/SupplyServiceTest.java
Labels: implementation

#250 BID UD Done #229
  Front End/my-app/src/components/Store/BID/AddProduct.js
  Front End/my-app/src/components/Store/BID/AllOffers.js
  Front End/my-app/src/components/Store/BID/BID.js
  Front End/my-app/src/components/Store/BID/BIDItem.css
  Front End/my-app/src/components/Store/BID/BIDItem.js
  Front End/my-app/src/components/Store/BID/MainBID.js
  Front End/my-app/src/components/Store/BID/Offer.js
  Front End/my-app/src/components/Store/BID/Option.js
  Front End/my-app/src/components/Store/BID/Options.js
  Front End/my-app/src/components/Store/Store.js
Labels: UI

#251 New react
  Front End/my-app/src/components/BuyingPolicy/simpleBuyingRules/ProductRule.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/AddCombineRule.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/AndRule.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/BigOrFirst.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/CategoryDiscout.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/OrRule.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/XorRule.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/AddComposeDiscount.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/AndRule.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/BigOrFirst.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/CategoryDiscount.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/MoreRule.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/OrRule.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/XorRule.js
  Front End/my-app/src/components/DiscountPolicy/SimpleRules/AddSimpleRule.js
  Front End/my-app/src/components/DiscountPolicy/SimpleRules/SimpleDisountRule.js
  Front End/my-app/src/components/Store/BID/AllOffers.js
  Front End/my-app/src/components/Store/BID/BID.js
  Front End/my-app/src/components/Store/BID/CreateBID.js
  Front End/my-app/src/components/Store/BID/MyBIDs.js
  Front End/my-app/src/components/Store/BID/Offer.js
  Front End/my-app/src/components/Store/BID/Status.js
  Front End/my-app/src/components/Store/BuyingPolicy.js
  Front End/my-app/src/components/Store/Store.js
Labels: UI

#256 #186 fixed policies for GUI and BID
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BID.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/AndBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/CategoryBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/ConditioningBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/OrBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/ProductBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/ShoppingBagBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/UserBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/AddDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/AndDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/ConditionCategoryDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/ConditionProductDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/ConditionStoreDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/OrDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/SimpleCategoryDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/SimpleProductDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/SimpleStoreDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/XorDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Store.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/IMarket.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/BuyRules/AndBuyRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/BuyRules/CategoryBuyRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/BuyRules/CompositionBuyRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/BuyRules/ConditioningBuyRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/BuyRules/LeafBuyRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/BuyRules/OrBuyRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/BuyRules/ProductBuyRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/BuyRules/ShoppingBagBuyRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/BuyRules/UserBuyRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/DiscountRules/AddDiscountRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/DiscountRules/AndDiscountRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/DiscountRules/CompositionDiscountRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/DiscountRules/ConditionCategoryDiscountRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/DiscountRules/ConditionProductDiscountRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/DiscountRules/ConditionStoreDiscountRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/DiscountRules/LeafDiscountRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/DiscountRules/OrDiscountRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/DiscountRules/SimpleCategoryDiscountRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/DiscountRules/SimpleProductDiscountRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/DiscountRules/SimpleStoreDiscountRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/DiscountRules/XorDiscountRuleSL.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/PurchaseTest.java
  market-spring-boot/src/test/java/com/example/Integration/StoreAndPolicies.java
Labels: implementation

#260 BID test + get BIDS X2 , Fixed pay
  market-spring-boot/src/main/java/com/example/demo/Domain/ErrorCode.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Purchase.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BID.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Inventory.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Store.java
  market-spring-boot/src/main/java/com/example/demo/ExternalService/PaymentService.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/IMarket.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/ServiceBID.java
  market-spring-boot/src/main/java/com/example/demo/Service/TestableFacade.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/MarketBridge.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/ProxyMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/RealMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/ConcurrentPurchaseTest.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/PurchaseTest.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/SystemManagerTests.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/SystemTests.java
  market-spring-boot/src/test/java/com/example/Unit/StoreModel/BIDTest.java
  market-spring-boot/src/test/java/com/example/Unit/StoreModel/StoreTest.java
Labels: bug, implementation, testing

#261 Fix tests
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/permissionType.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyPolicy.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyStrategy.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountPolicy.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Store.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/Validator.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/MarketBridge.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/ProxyMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/RealMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/PurchaseTest.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/StoreOwnerTests.java
  market-spring-boot/src/test/java/com/example/Integration/StoreMarketTest.java
  market-spring-boot/src/test/java/com/example/Unit/Market/MarketTest.java
Labels: bug, testing

#265 fixed bug add shoppingCart & manage list approves
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BID.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/XorDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Store.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/UserManager.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/DiscountRules/XorDiscountRuleSL.java
Labels: bug

#266 #166
  Front End/my-app/src/App.js
  Front End/my-app/src/client/clientHttp.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/AddCombineRule.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/BigOrFirst.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/AddRule.js
  Front End/my-app/src/components/Manager/UserID.js
  Front End/my-app/src/components/Manager/UserList.js
  Front End/my-app/src/components/Store/RemoveManager.js
  Front End/my-app/src/components/Store/Store.js
Labels: UI

#268 add AT for BID
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BID.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Store.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/MarketBridge.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/ProxyMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/RealMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/PurchaseTest.java
  market-spring-boot/src/test/java/com/example/Unit/StoreModel/BIDTest.java
Labels: testing

#269 Da
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/AlertService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/AlertServiceDemo.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/IAlertService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/Notification.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/User.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/UserManager.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/Validator.java
  market-spring-boot/src/main/resources/application.properties
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/SystemTests.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/NotificationServiceTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/UserServiceTest.java
  market-spring-boot/src/test/java/com/example/demo/Domain/UserModel/ValidatorTest.java
Labels: implementation

#270 Buy
  Front End/my-app/src/components/Store/BID/BID.js
  Front End/my-app/src/components/Store/BID/BuyBID.js
  Front End/my-app/src/components/Store/BID/MyBIDs.js
  Front End/my-app/src/components/Store/BID/Status.js
Labels: UI

#271 lowercase + da services - fixed #220
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataInventory.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataShoppingBag.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataShoppingCart.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataUser.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/InventoryRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/ShoppingCartRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/DataServices.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/ProductTypeService.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/ShoppingBagService.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/UserService.java
  market-spring-boot/src/main/java/com/example/demo/DemoApplication.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/ShoppingCart.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/User.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/UserManager.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/TestableFacade.java
  market-spring-boot/src/test/java/com/example/Integration/StoreMarketTest.java
  market-spring-boot/src/test/java/com/example/Integration/UserMangerMarketTest.java
  market-spring-boot/src/test/java/com/example/Unit/Market/MarketTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/ProductTypeServiceTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/StoreServiceTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/UserServiceTest.java
Labels: bug

#273 #166
  Front End/my-app/src/components/Bar/SignUp.js
  Front End/my-app/src/components/DiscountPolicy/CombineRules/AndRule.js
  Front End/my-app/src/components/DiscountPolicy/ComposeRules/AndRule.js
  Front End/my-app/src/components/DiscountPolicy/SimpleRules/AddSimpleRule.js
  Front End/my-app/src/components/DiscountPolicy/SimpleRules/ConditionCategoryDiscountRule.js
  Front End/my-app/src/components/DiscountPolicy/SimpleRules/ConditionProductDiscountRule.js
  Front End/my-app/src/components/DiscountPolicy/SimpleRules/ConditionStoreDiscountRule.js
  Front End/my-app/src/components/Market/Profile.js
  Front End/my-app/src/components/Store/HistoryInStore.js
  Front End/my-app/src/components/Store/Store.js
Labels: UI

#272 change return from purchase
  market-spring-boot/src/main/java/Stabs/PurchaseStab.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/DetailsPurchase.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Purchase.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/SaleObj.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/IMarket.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/ServiceDetailsPurchase.java
  market-spring-boot/src/main/java/com/example/demo/api/Iapi.java
  market-spring-boot/src/main/java/com/example/demo/api/api.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/MarketBridge.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/ProxyMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/RealMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/ConcurrentPurchaseTest.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/ConcurrentRemoveProductAndPurchaseTest.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/PurchaseTest.java
  market-spring-boot/src/test/java/com/example/Unit/ExternalServices/PurchaseUnitTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/RuleServiceTest.java
Labels: implementation

#275 DB buyRules + getShoppingBag more info
  market-spring-boot/pom.xml
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/RuleService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/AndBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/BuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/CategoryBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/CompositionBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/ConditioningBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/LeafBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/OrBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/ProductBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/ShoppingBagBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/UserBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/ConditionCategoryDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/ConditionProductDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/ConditionStoreDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Predicate/CategoryPred.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Predicate/Predicate.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Predicate/ProductPred.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Predicate/ShoppingBagPred.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Predicate/UserPred.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/ShoppingBag.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/ServiceShoppingBag.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/ServiceShoppingCart.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/RuleServiceTest.java
Labels: implementation

#276 #166
  Front End/my-app/src/App.js
  Front End/my-app/src/components/Bar/Bar.js
  Front End/my-app/src/components/Cart/BuyCart.js
  Front End/my-app/src/components/Cart/MyCart.js
  Front End/my-app/src/components/Manager/ManagerButton.js
  Front End/my-app/src/components/Market/Profile.js
  Front End/my-app/src/components/Store/BID/AllOffers.js
  Front End/my-app/src/components/Store/BID/MyBIDs.js
  Front End/my-app/src/components/Store/BID/Status.js
  Front End/my-app/src/components/Store/Store.js
Labels: UI

#280 DB + tests (Buy policy + Discount policy)
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/RuleService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyPolicy.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/BuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/CategoryBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/CompositionBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/ConditioningBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/LeafBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/ProductBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/ShoppingBagBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/UserBuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountPolicy.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/AddDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/AndDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/CompositionDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/ConditionCategoryDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/ConditionProductDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/ConditionStoreDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/DiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/LeafDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/OrDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/SimpleCategoryDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/SimpleProductDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/SimpleStoreDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/XorDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Store.java
  market-spring-boot/src/main/resources/application.properties
  market-spring-boot/src/test/java/com/example/Unit/StoreModel/BuyPolicyTest.java
  market-spring-boot/src/test/java/com/example/Unit/StoreModel/DiscountPoilicyTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/RuleServiceTest.java
Labels: implementation, testing

#284 fixed permission BID
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BID.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Store.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/PurchaseTest.java
  market-spring-boot/src/test/java/com/example/Unit/StoreModel/BIDTest.java
Labels: bug, implementation, testing

#285 #166
  Front End/my-app/src/components/Store/BID/BID.js
  Front End/my-app/src/components/Store/BID/Offer.js
Labels: UI

#286 Da
  market-spring-boot/env.json
  market-spring-boot/src/main/java/Stabs/UserManagerStab.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/CompositeKeys/ShoppingBagId.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataShoppingBag.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataStore.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataUser.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/ShoppingBagRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/DataServices.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/ShoppingBagService.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/UserService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/ProductType.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyPolicy.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/History.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/ShoppingBag.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/ShoppingCart.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/User.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/UserManager.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/ServiceObj/ServiceStore.java
  market-spring-boot/src/test/java/com/example/Unit/UserModel/ShoppingBagTest.java
  market-spring-boot/src/test/java/com/example/Unit/UserModel/ShoppingCartTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/ProductTypeServiceTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/RuleServiceTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/ShoppingBagServiceTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/StoreServiceTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/UserServiceTest.java
Labels: implementation

#287 Da
  Front End/my-app/package-lock.json
  Front End/my-app/src/client/clientHttp.js
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/AlertService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/NotificationDispatcher.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/UserManager.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/IMarket.java
  market-spring-boot/src/main/java/com/example/demo/api/Iapi.java
  market-spring-boot/src/main/java/com/example/demo/api/api.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/MarketBridge.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/ProxyMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Bridge/RealMarket.java
  market-spring-boot/src/test/java/com/example/Acceptance/Tests/SystemTests.java
Labels: bug

#289 bug fix modify messages
  Front End/my-app/src/App.js
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataNotification.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/AlertService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/AlertServiceDemo.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/IAlertService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/Notification.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/NotificationController.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/NotificationDispatcher.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/UserManager.java
  market-spring-boot/src/main/resources/application.properties
Labels: bug

#290 Da
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataPermission.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataProductStore.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/PermissionRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/ProductStoreRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/ProductTypeRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/StoreRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/DataServices.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/PermissionService.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/ProductStoreService.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/ProductTypeService.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/StoreService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Permission.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/PermissionManager.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/ProductType.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Inventory.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Store.java
  market-spring-boot/src/main/java/com/example/demo/Domain/UserModel/UserManager.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/PermissionServiceTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/ProductTypeServiceTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/StoreServiceTest.java
Labels: implementation, testing

#291 add get rule info
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataStore.java
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyPolicy.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BuyRules/BuyRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountPolicy.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/CompositionDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/DiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/DiscountRule/LeafDiscountRule.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Inventory.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Store.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/IMarket.java
  market-spring-boot/src/main/java/com/example/demo/api/Iapi.java
  market-spring-boot/src/main/java/com/example/demo/api/api.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/RuleServiceTest.java
Labels: implementation

#292 add get rule info with http client
  Front End/my-app/src/client/clientHttp.js
Labels: implementation

#294 #166
  Front End/my-app/src/components/Bar/Bar.js
  Front End/my-app/src/components/BuyingPolicy/RuleInfo.js
  Front End/my-app/src/components/Store/Store.js
  Front End/my-app/src/components/Store/newStore.js
Labels: UI

#293 add is founder func
  Front End/my-app/src/client/clientHttp.js
  market-spring-boot/src/main/java/com/example/demo/Domain/Market/Market.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/Service/IMarket.java
  market-spring-boot/src/main/java/com/example/demo/api/Iapi.java
  market-spring-boot/src/main/java/com/example/demo/api/api.java
  market-spring-boot/src/main/java/com/example/demo/api/apiObjects/bridge/proxy.java
Labels: implementation

#295 DA
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataHistory.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataUser.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/HistoryRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/HistoryService.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/PermissionService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/History.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/ProductStore.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Store.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/HistoryServiceTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/PermissionServiceTest.java
Labels: implementation

#296 #166
  Front End/my-app/src/components/BuyingPolicy/RuleID.js
  Front End/my-app/src/components/BuyingPolicy/RuleInfo.js
  Front End/my-app/src/components/BuyingPolicy/RuleList.js
  Front End/my-app/src/components/BuyingPolicy/SimpleCompose/ConditionRule.js
  Front End/my-app/src/components/BuyingPolicy/buyingPolicy.js
  Front End/my-app/src/components/DiscountPolicy/AllRules.js
  Front End/my-app/src/components/DiscountPolicy/RuleID.js
  Front End/my-app/src/components/DiscountPolicy/RuleInfo.js
  Front End/my-app/src/components/DiscountPolicy/RuleList.js
  Front End/my-app/src/components/Store/Store.js
Labels: UI

#298 Da
  market-spring-boot/env.json
  market-spring-boot/src/main/java/com/example/demo/DataAccess/CompositeKeys/BIDID.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataBID.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataShoppingBag.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataStore.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Enums/Status.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/BIDRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/BIDService.java
  market-spring-boot/src/main/java/com/example/demo/DemoApplication.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Store.java
  market-spring-boot/src/main/java/com/example/demo/configuration/JsonInit.java
  market-spring-boot/src/main/resources/application.properties
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/BIDServiceTest.java
Labels: implementation

#299 added functions to permission service
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Repository/PermissionRepository.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/PermissionService.java
  market-spring-boot/src/main/resources/application.properties
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/PermissionServiceTest.java
Labels: implementation

#300 added functions to permission service
  market-spring-boot/env.json
  market-spring-boot/src/main/java/com/example/demo/DemoApplication.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/java/com/example/demo/configuration/StateInit/Initilizer.java
Labels: bug

#301 add BID for db and domain
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/BIDService.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/DataServices.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/BID.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Inventory.java
  market-spring-boot/src/main/java/com/example/demo/Domain/StoreModel/Store.java
  market-spring-boot/src/main/java/com/example/demo/Service/Facade.java
  market-spring-boot/src/main/resources/application.properties
  market-spring-boot/src/test/java/com/example/Unit/StoreModel/BIDTest.java
  market-spring-boot/src/test/java/com/example/demo/DataAccess/Services/BIDServiceTest.java
Labels: implementation

#303 fix bug db
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataHistory.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataProductType.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataStore.java
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Entity/DataUser.java
Labels: bug

#304 Connection to db failure broadcast
  market-spring-boot/env.json
  market-spring-boot/src/main/java/com/example/demo/DataAccess/Services/UserService.java
  market-spring-boot/src/main/java/com/example/demo/DemoApplication.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/AlertService.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/Notification.java
  market-spring-boot/src/main/java/com/example/demo/Domain/AlertService/NotificationDispatcher.java
  market-spring-boot/src/main/java/com/example/demo/configuration/JsonInit.java
  market-spring-boot/src/main/resources/application.properties
Labels: implementation

#309 added docu
  Files/version 3 - files/Architcture Diagram.drawio
  Files/version 3 - files/Architcture Diagram.pdf
  Files/version 3 - files/DB.png
  Files/version 3 - files/Load and stress system test.pptx
  Files/version 3 - files/state system doc.pdf
  Files/version 3 - files/white diagram.drawio
  Files/version 4 - files/Architcture Diagram.drawio
  Files/version 4 - files/Architcture Diagram.pdf
Labels: documentation
